// Transforms a Hook[] selection into installable artifacts: merged settings.json, scripts, plugin zip, or standalone install script.
import type { Hook } from '@/types/hook'

type HookEntry = { matcher?: string; hooks: unknown[] }
type HooksMap = Record<string, HookEntry[]>

function toBase64(str: string): string {
  const bytes = new TextEncoder().encode(str)
  let bin = ''
  for (const b of bytes) bin += String.fromCharCode(b)
  return btoa(bin)
}

export function mergeSettings(hooks: Hook[]): { hooks: HooksMap } {
  const merged: HooksMap = {}

  for (const hook of hooks) {
    const fragment = (hook.implementation.config as { hooks?: HooksMap }).hooks
    if (!fragment) continue

    for (const [event, entries] of Object.entries(fragment)) {
      merged[event] ??= []
      for (const entry of entries) {
        const existing = merged[event].find((e) => (e.matcher ?? '') === (entry.matcher ?? ''))
        if (existing) {
          existing.hooks.push(...entry.hooks)
        } else {
          merged[event].push({ ...entry, hooks: [...entry.hooks] })
        }
      }
    }
  }

  return { hooks: merged }
}

export function toSettingsJson(hooks: Hook[]): string {
  return JSON.stringify(mergeSettings(hooks), null, 2)
}

export function collectScripts(hooks: Hook[]): { path: string; content: string }[] {
  return hooks
    .filter((h) => h.implementation.script_path && h.implementation.code_snippet)
    .map((h) => ({
      path: h.implementation.script_path as string,
      content: h.implementation.code_snippet as string,
    }))
}

export function toPluginFiles(hooks: Hook[]): Record<string, string> {
  const merged: HooksMap = {}

  for (const hook of hooks) {
    const fragment = (hook.implementation.config as { hooks?: HooksMap }).hooks
    if (!fragment) continue

    const snippet = hook.implementation.code_snippet

    for (const [event, entries] of Object.entries(fragment)) {
      merged[event] ??= []
      for (const entry of entries) {
        const adaptedHooks = (entry.hooks as Array<{ type: string; command?: string }>).map(h => {
          if (snippet && h.command?.includes('/.claude/hooks/')) {
            return { ...h, command: `bash -c "$(echo '${toBase64(snippet)}' | base64 -d)"` }
          }
          return h
        })
        const existing = merged[event].find(e => (e.matcher ?? '') === (entry.matcher ?? ''))
        if (existing) {
          existing.hooks.push(...adaptedHooks)
        } else {
          merged[event].push({ ...entry, hooks: adaptedHooks })
        }
      }
    }
  }

  return {
    '.claude-plugin/plugin.json': JSON.stringify(
      {
        name: 'hookstack-selection',
        description: `Hookstack — ${hooks.map(h => h.slug).join(', ')}`,
        version: '1.0.0',
      },
      null,
      2,
    ),
    'hooks/hooks.json': JSON.stringify({ hooks: merged }, null, 2),
  }
}

export function generateInstallScript(hooks: Hook[]): string {
  const config = mergeSettings(hooks)
  const scripts = collectScripts(hooks)

  const configJson = JSON.stringify(config, null, 2)
  const scriptsJson = JSON.stringify(scripts, null, 2)

  return `#!/usr/bin/env node
// Generated by Hookstack — https://www.hookstack.app/en
// Run from your project root: node install-hooks.mjs

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { join } from 'path'

const ROOT = process.cwd()
const SETTINGS_PATH = join(ROOT, '.claude', 'settings.json')
const HOOKS_DIR = join(ROOT, '.claude', 'hooks')

const newConfig = ${configJson}

const scripts = ${scriptsJson}

function mergeHooks(existing, incoming) {
  const merged = structuredClone(existing)
  for (const [event, entries] of Object.entries(incoming)) {
    merged[event] ??= []
    for (const entry of entries) {
      const found = merged[event].find(e => (e.matcher ?? '') === (entry.matcher ?? ''))
      if (found) {
        found.hooks.push(...entry.hooks)
      } else {
        merged[event].push({ ...entry, hooks: [...entry.hooks] })
      }
    }
  }
  return merged
}

let settings = {}
if (existsSync(SETTINGS_PATH)) {
  settings = JSON.parse(readFileSync(SETTINGS_PATH, 'utf8'))
  console.log('  settings.json existant trouvé, fusion en cours...')
} else {
  console.log('  Aucun settings.json existant, création...')
}

settings.hooks = mergeHooks(settings.hooks ?? {}, newConfig.hooks)

mkdirSync(join(ROOT, '.claude'), { recursive: true })
writeFileSync(SETTINGS_PATH, JSON.stringify(settings, null, 2))
console.log('  .claude/settings.json mis à jour')

if (scripts.length > 0) {
  mkdirSync(HOOKS_DIR, { recursive: true })
  for (const script of scripts) {
    writeFileSync(join(ROOT, script.path), script.content, 'utf8')
    console.log(\`  \${script.path} créé\`)
  }
}

console.log('\\n✅ Installation terminée !')
console.log('   Relance Claude Code pour activer les nouveaux hooks.')
`
}
